import { Step } from './types';

// Steps 1-5: Zoom Controls to Helper Features
export const stepsFirstHalf: Step[] = [
  {
    id: 1,
    title: "Zoom Controls",
    icon: "🔍",
    color: "blue",
    action: "Control map zoom level (0-21)",
    result: "Navigate closer or farther from the map view",
    details: [
      "Location: Top-right toolbar",
      "Zoom In (+): Increases zoom by 1 level",
      "  • Button click, keyboard '+', double-click map",
      "  • Mouse wheel up, pinch gesture (touch)",
      "Zoom Out (-): Decreases zoom by 1 level",
      "  • Button click, keyboard '-', mouse wheel down",
      "Zoom Range: 0 (world view) to 21 (street level)",
      "Smooth Animation: 300ms transition",
      "Box Zoom: Shift + drag to draw zoom area",
      "Current zoom level displayed in settings",
    ],
  },
  {
    id: 2,
    title: "Map Type Selector",
    icon: "🗺️",
    color: "green",
    action: "Switch between 4 different map visualization types",
    result: "Change map display style for different use cases",
    details: [
      "Location: Top-right toolbar (near zoom controls)",
      "4 Map Types Available:",
      "  1. 🛣️ Roadmap (Default): Streets, labels, borders",
      "     • Best for: Navigation, street names",
      "  2. 🛰️ Satellite: Aerial imagery without labels",
      "     • Best for: Terrain analysis, vegetation",
      "  3. 🗺️📡 Hybrid: Satellite + road overlay (⭐ Recommended)",
      "     • Best for: Telecom network planning",
      "  4. ⛰️ Terrain: Topographic with elevation",
      "     • Best for: RF planning, LOS analysis",
      "Selection saved to your map preferences (browser storage where available)",
      "Persists across sessions and devices when supported",
    ],
  },
  {
    id: 3,
    title: "View Controls",
    icon: "🖥️",
    color: "purple",
    action: "Adjust map display size and mode",
    result: "Optimize screen space for better visualization",
    details: [
      "Full Screen Mode (🖥️):",
      "  • Toggle full browser window display",
      "  • Hides navigation bar and sidebar",
      "  • Exit: Button click or ESC key",
      "  • Uses browser fullscreen API when available",
      "",
      "Resize Map (↔️):",
      "  • Expand: Minimize sidebar, maximize map",
      "  • Collapse: Restore sidebar to normal",
      "  • Maintains current zoom and center",
      "  • Smooth 300ms width transition",
      "",
      "Live Location/GPS (📍):",
      "  • Requires browser geolocation (HTTPS)",
      "  • Shows blue dot at current position",
      "  • Accuracy circle shows GPS precision",
      "  • Real-time position tracking",
    ],
  },
  {
    id: 4,
    title: "Map Utilities",
    icon: "🛠️",
    color: "cyan",
    action: "Refresh data and configure map preferences",
    result: "Keep map data current and customize settings",
    details: [
      "Refresh Map (🔄):",
      "  • Reloads visible infrastructure items on the map",
      "  • Re-fetches data for the current viewport",
      "  • Updates layer visibility states",
      "  • Clears temporary drawing states",
      "  • Maintains current position and zoom",
      "",
      "Map Settings (⚙️):",
      "  Opens comprehensive settings panel with 5 categories:",
      "  1. Default View: Center lat/lng, zoom, map type",
      "  2. Display Options: Traffic, transit, bicycle, street view",
      "  3. Measurement Units: Metric (m, km) or Imperial (ft, mi)",
      "  4. Layer Defaults: Auto-load, visibility, clustering threshold",
      "  5. Performance: Clustering, max markers, auto-refresh interval",
      "  • Saved to your map preferences (user-facing setting)",
      "  • Persists across sessions when supported",
    ],
  },
  {
    id: 5,
    title: "Helper Features",
    icon: "ℹ️",
    color: "orange",
    action: "Get coordinates and access documentation",
    result: "Quick reference and location information",
    details: [
      "Live Coordinates Display (🧭):",
      "  • Location: Bottom-left or top-left corner",
      "  • Format: 'Lat: 28.6139, Lng: 77.2090'",
      "  • Real-time updates as mouse moves",
      "  • Precision: 4 decimal places (approx. ±11m accuracy)",
      "  • Click to copy coordinates to clipboard",
      "  • Use cases: Tower location, POP verification",
      "",
      "Help & Documentation (❓):",
      "  Opens comprehensive help panel:",
      "  • Quick Start Guide: Getting started",
      "  • GIS Tools Tutorial: Step-by-step for each tool",
      "  • Keyboard Shortcuts:",
      "    - '+ / -' : Zoom in/out",
      "    - 'ESC' : Close active tool/modal",
      "    - 'F' : Toggle full screen",
      "    - 'L' : Toggle layer panel",
      "    - '/' : Focus search box",
      "  • Video Tutorials: Embedded demos",
      "  • FAQ: Common questions",
      "  • Contact Support: Email/chat links",
    ],
  },
];

