import { Step, ProTip } from './types';

// Steps 6-9: Interactive Legend to Performance Optimization
export const stepsSecondHalf: Step[] = [
  {
    id: 6,
    title: "Interactive Legend Panel",
    icon: "🎨",
    color: "pink",
    action: "View and toggle map layers and markers",
    result: "Understand map symbols and control visibility",
    details: [
      "Location: Top-right or bottom-right corner",
      "Toggle: Click to show/hide",
      "",
      "Content Sections:",
      "1. Infrastructure Types (7 types):",
      "   🔴 POP (Point of Presence)",
      "   🟠 SubPOP",
      "   🔵 Tower",
      "   🟢 Building",
      "   🟣 Customer",
      "   🟡 Fiber Route",
      "   🩷 Junction Box",
      "",
      "2. Status Indicators (4 states):",
      "   🟢 Active | 🔴 Inactive | 🟡 Maintenance | ⚪ Planned",
      "",
      "3. GIS Layers (5 layer types):",
      "   Blue line: Distance Measurement",
      "   Green square: Polygon Drawing",
      "   Purple circle: Circle Drawing",
      "   Red triangle: RF Sector",
      "",
      "4. Elevation Profile: Color gradient (Low ◄─► High)",
      "",
      "Features:",
      "  • Dynamic: Updates based on visible layers",
      "  • Interactive: Click to toggle layer visibility",
      "  • Draggable: Reposition anywhere on map",
      "  • Smart: Hides irrelevant items when layers are off",
    ],
  },
  {
    id: 7,
    title: "Layer Panel",
    icon: "📚",
    color: "indigo",
    action: "Manage and toggle GIS data layers",
    result: "Control visibility of different data types",
    details: [
      "Location: Right sidebar or floating panel",
      "Toggle Visibility: Checkbox for each layer",
      "",
      "Available Layers:",
      "  • Infrastructure Items (POP, Tower, Building, etc.)",
      "  • Distance Measurements",
      "  • Elevation Profiles",
      "  • Polygon Drawings",
      "  • Circle Drawings",
      "  • RF Sectors",
      "  • Custom Bookmarks",
      "",
      "Layer Controls:",
      "  • Show/Hide All: Toggle all layers at once",
      "  • Opacity Slider: Adjust layer transparency",
      "  • Z-Index Control: Change layer stacking order",
      "  • Filter by Region: Show only specific regions",
      "  • Filter by Status: Active, Inactive, Maintenance",
      "",
      "Performance Features:",
      "  • Lazy loading: Only load visible layers",
      "  • Clustering: Group nearby markers for clarity",
      "  • Viewport-based loading: Fetch only the visible area",
    ],
  },
  {
    id: 8,
    title: "Global Search",
    icon: "🔎",
    color: "red",
    action: "Search infrastructure items and locations",
    result: "Quickly find and navigate to specific items",
    details: [
      "Location: Top-right corner of map",
      "Search Types:",
      "  1. Infrastructure Search:",
      "     • By name, ID, or type",
      "     • By location (address, coordinates)",
      "     • By region (state, city, area)",
      "  2. Location Search:",
      "     • Address lookup with geocoding",
      "     • Coordinate search (lat, lng)",
      "     • Landmark search",
      "",
      "Features:",
      "  • Autocomplete: Suggestions as you type",
      "  • Debounced: Small delay prevents excessive requests",
      "  • History: Recent searches saved locally",
      "  • Filters: Type, status, region",
      "  • Results: Click to zoom and highlight",
      "",
      "Search Results:",
      "  • Shows a limited, relevant set of results",
      "  • Displays: Name, type, location, status",
      "  • Click result: Map zooms to item",
      "  • Marker highlight: Short pulsing animation",
      "  • Info window: Shows full item details",
      "",
      "Keyboard Shortcut: '/' to focus search box",
    ],
  },
  {
    id: 9,
    title: "Performance Optimization",
    icon: "⚡",
    color: "yellow",
    action: "Understand how the map handles large datasets",
    result: "Smooth performance with large marker sets",
    details: [
      "Marker Clustering:",
      "  • Groups nearby markers to reduce clutter",
      "  • Shows count badge on cluster",
      "  • Click cluster to zoom in and expand",
      "  • Color-coded by density for quick insight",
      "",
      "Viewport Queries:",
      "  • Only loads infrastructure within the visible area",
      "  • Fetches data relevant to current map bounds",
      "  • Updates automatically on pan/zoom",
      "",
      "Debounced Search:",
      "  • Brief delay prevents excessive requests",
      "  • Cancels previous work on new input",
      "",
      "Overlay Management:",
      "  • Creates/destroys overlays based on visibility",
      "  • Reuses overlay objects when possible",
      "  • Cleans up memory on unmount",
      "",
      "Smooth Animations:",
      "  • 300ms transitions for zoom, pan, resize",
      "  • Uses requestAnimationFrame when possible",
      "  • GPU acceleration for transforms",
      "",
      "Caching:",
      "  • Viewport data may be temporarily cached for responsiveness",
      "  • Map tiles cached by the map provider",
      "  • User preferences stored locally where supported",
    ],
  },
];

// Pro tips data
export const proTips: ProTip[] = [
  { label: "Use Hybrid Map Type", content: "for best telecom network planning visualization (satellite + roads)." },
  { label: "Keyboard Shortcuts", content: "save time: Use '+/-' for zoom, 'F' for fullscreen, '/' for search." },
  { label: "Click Legend Items", content: "to quickly toggle layer visibility without opening the layer panel." },
  { label: "Marker Clustering", content: "groups markers for better readability when many items are visible." }
];

