export const VISIBLE_PERMISSIONS = {
  map: [
    "map:view",
    "map:tools:geometry_suite",
    "network:feasibility:view",
    "network:feasibility:edit",
    "network:feasibility:markers",
  ],
  network: [
    "network:infra:items",
    "network:infra:approve",
    "network:infra:submissions",
    "network:infra:delete",
    "network:infra:add",
    "network:recycle_bin",
    "network:recycle:restore",
    "network:recycle:delete",
    "network:folder:create",
    "network:folder:rename",
    "network:folder:delete",
    "network:file:import",
    "network:manage_features",
    "network:file:edit_planned",
    "network:file:live_edit_planned",
    "network:file:delete_file_planned",
    "network:file:delete_feature_planned",
    "network:file:edit_live",
    "network:file:live_edit_live",
    "network:file:delete_file_live",
    "network:file:delete_feature_live",
    "network:file:edit_imported",
    "network:file:live_edit_imported",
    "network:file:delete_file_imported",
    "network:file:delete_feature_imported",
    "network:tools:export",
    // Hidden but required for network functionality
    "network:view",
    "network:map:view",
  ],
  dashboard: ["dashboard:view"],
  users: [
    "users:view",
    "users:create",
    "users:edit",
    "users:delete",
    "users:manage_permissions",
    "users:reset_password",
    "users:manage_security",
    "users:import",
    "users:export",
  ],
  groups: ["groups:view", "groups:create", "groups:edit", "groups:delete"],
  admin: [
    "admin:view",
    "admin:audit_logs",
    "admin:audit_logs:export",
    "admin:audit_logs:clear",
    "admin:region_request",
    "admin:bulk_assignment",
    "admin:temp_access",
    "admin:export_reports",
    "admin:password_reset",
    "admin:region_boundaries",
    "admin:database",
    "admin:database:export",
    "data:export",
    "admin:role_builder",
  ],
  analytics: ["analytics:view"],
  help: [
    "system:schema:view",
    "system:schema:export:pdf",
    "system:schema:export:image",
    "system:schema:annotate",
    "system:schema:query",
    "system:schema:erd",
    "system:api:view",
    "system:api:export",
    "system:api:edit",
    "system:architecture:view",
  ],
  regions: [],
  converters: [
    "converter:view",
    "converter:excel_to_kml"
  ],
  darkfiber: [
    "darkfiber:view"
  ]
};
