import { Step } from './types';

export const steps: Step[] = [
  {
    id: 1,
    title: "Open Tool",
    icon: "🎯",
    color: "orange",
    action: "Click 'Circle Drawing Tool' button in Map toolbar",
    result: "Tool panel appears, cursor changes to crosshair (+)",
    details: [
      "Navigate to Map Page (http://localhost:3005/map)",
      "Click on 'Circle Drawing Tool' button in toolbar",
      "Or select from GIS Tools dropdown menu",
      "Tool panel overlay appears on map",
      "Map cursor changes to crosshair (+)",
      "Status: 'Click on map to place circle center'",
      "Default radius: 1000 meters (1 km)",
    ],
  },
  {
    id: 2,
    title: "Place Circle Center",
    icon: "📍",
    color: "blue",
    action: "Click anywhere on map to place circle center",
    result: "Circle appears instantly with center marker",
    details: [
      "Click anywhere on the map",
      "Center marker appears at clicked location",
      "Coordinates captured: { lat, lng }",
      "⭕ Circle drawn with default 1000m radius",
      "🔴 Red fill color (default #FF0000)",
      "📏 Semi-transparent (35% opacity default)",
      "Status: 'Circle placed. Adjust radius or customize.'",
    ],
  },
  {
    id: 3,
    title: "View Circle Elements",
    icon: "👁️",
    color: "green",
    action: "Observe all visual elements on map",
    result: "Complete circle with interactive handles visible",
    details: [
      "📍 Center Marker: Pin at exact circle center",
      "⭕ Circle Fill: Semi-transparent colored area",
      "🔴 Circle Border: 2px stroke outline",
      "🔵 Resize Handles: 4 blue squares at N, S, E, W",
      "↔️ Draggable: Click inside to move entire circle",
      "📊 Info Panel shows: Radius, Area, Perimeter",
      "📍 Center coordinates displayed",
    ],
  },
  {
    id: 4,
    title: "Adjust Radius",
    icon: "📏",
    color: "indigo",
    action: "Change circle size using 3 methods",
    result: "Circle resizes with auto-calculated measurements",
    details: [
      "Method 1: Type radius in input field → Press Enter",
      "Method 2: Click & drag blue handles (resize)",
      "Method 3: Use radius slider (100m - 50km)",
      "📊 Area recalculates: π × radius²",
      "📏 Perimeter recalculates: 2 × π × radius",
      "⭕ Circle redraws on map instantly",
      "✅ Real-time updates while adjusting",
    ],
  },
  {
    id: 5,
    title: "Move Circle",
    icon: "↔️",
    color: "purple",
    action: "Drag circle to new location",
    result: "Circle relocates with center coordinates updated",
    details: [
      "Click anywhere inside the circle (not on edges)",
      "Hold mouse button and drag",
      "Circle moves in real-time",
      "📍 Center marker moves with circle",
      "📊 Area and perimeter stay same",
      "📝 Center coordinates update in panel",
      "✅ Boundary validation: Stays within India",
      "⚠️ Warning if moved outside boundary",
    ],
  },
  {
    id: 6,
    title: "Customize Appearance",
    icon: "🎨",
    color: "pink",
    action: "Change color and opacity settings",
    result: "Circle updates with new visual styling",
    details: [
      "🎨 Click color swatch to open picker",
      "🎨 Select RGB/Hex color",
      "🔴 Default: Red (#FF0000)",
      "✅ Changes both fill & stroke color",
      "💧 Adjust opacity slider (0-100%)",
      "💧 Default: 35% transparency",
      "✅ Real-time preview on map",
      "Examples: Coverage zones, danger zones, service areas",
    ],
  },
  {
    id: 7,
    title: "Reset or Clear",
    icon: "↩️",
    color: "red",
    action: "Use Reset to restore defaults or Clear to remove",
    result: "Circle resets or removes from map",
    details: [
      "Reset Button: Returns radius to 1000m default",
      "Keeps center location unchanged",
      "Keeps color & opacity settings",
      "✅ No confirmation needed for reset",
      "Clear Button: Removes circle completely",
      "⚠️ Confirmation dialog: 'Clear circle?'",
      "Removes center marker too",
      "✅ Tool remains open for new circle",
    ],
  },
  {
    id: 8,
    title: "Save Circle",
    icon: "💾",
    color: "teal",
    action: "Click Save button and choose storage type",
    result: "Save dialog opens with storage options",
    details: [
      "Click 'Save' button in tool panel",
      "Enter Circle Name (required field)",
      "Add Description/Notes (optional)",
      "View calculated metrics summary",
      "Choose storage type (app-level): Permanent (saved to My Data) or Temporary (session)",
      "Click 'Save' to confirm",
    ],
  },
  {
    id: 9,
    title: "Where Data is Saved",
    icon: "💽",
    color: "cyan",
    action: "Data stored based on selected type",
    result: "Circle saved to the selected in-app storage option",
    details: [
      "Permanent: Saved to 'My Data' within the app (accessible across sessions/devices depending on app settings)",
      "Temporary: Saved to current session cache (cleared on browser close or session expiry)",
      "Saved circles appear in the My Data section for quick access",
      "Temporary items appear only for the active session",
    ],
  },
  {
    id: 10,
    title: "Access Saved Data",
    icon: "📂",
    color: "violet",
    action: "Retrieve circles from multiple locations inside the app",
    result: "View, edit, or export circle data",
    details: [
      "1️⃣ GIS Data Hub → My Data → Circles",
      "2️⃣ Map Layers → Toggle 'Circles' ON",
      "3️⃣ Circle Tool → Load Saved dropdown",
      "4️⃣ Global Search → Type circle name",
      "5️⃣ Export: KML/GeoJSON/CSV/Excel",
      "6️⃣ Session Storage (temporary only)",
    ],
  },
];

