// Domain and UI type barrels

export type {
  // UI types
  UIState,
  ThemeType,
  ThemeConfig,
  ThemeColors,
  ColorPalette,
  SemanticColors,
  SurfaceColors,
  TextColors,
  BorderColors,
  ThemeFonts,
  ThemeSpacing,
  ThemeShadows,
  ThemeAnimations,
  LayoutState,
  SidebarState,
  HeaderState,
  FooterState,
  WorkspaceState,
  WorkspaceConfig,
  ComponentConfig,
  ResponsiveState,
  NavigationState,
  Breadcrumb,
  MenuItem,
  NavigationHistory,
  ModalState,
  Modal,
  ModalType,
  ModalSize,
  ModalPosition,
  ModalOptions,
  NotificationState,
  Notification,
  NotificationType as UINotificationType,
  NotificationPosition,
  NotificationAction,
  PanelState,
  Panel,
  PanelOptions,
  PanelBounds,
  LoadingState as UILoadingState,
  GlobalLoading,
  ComponentLoading,
  OperationLoading,
  PerformanceState,
  PerformanceMetrics as UIPerformanceMetrics,
  PerformanceAlert,
  FormState,
  FormConfig,
  FormField,
  InputType,
  SelectOption,
  FieldValidation,
  FormValidation,
  ValidationRule as UIValidationRule,
  AutoSaveConfig,
  AccessibilityState,
  Announcement,
  FocusManagement,
  SkipLink,
  KeyboardNavigation,
  KeyboardShortcut,
  ScreenReaderConfig,
} from "./ui/index";

export type {
  // Analytics types
  AnalyticsMetric,
  MetricCategory,
  MetricType,
  AggregationType,
  TimeSeriesData,
  TimeSeriesMetric,
  TimeGranularity,
  PerformanceMetrics as AnalyticsPerformanceMetrics,
  SystemPerformance,
  ApplicationPerformance,
  NetworkPerformance,
  UserExperienceMetrics,
  BusinessMetrics,
  RevenueMetrics,
  CostMetrics,
  ROIMetrics,
  MarketMetrics,
  MarketTrend,
  CustomerMetrics,
  NetworkAnalytics,
  CoverageAnalytics,
  CoverageGap,
  QualityAnalytics,
  QualityIssue,
  CapacityAnalytics,
  CapacityBottleneck,
  ExpansionNeed,
  UtilizationAnalytics,
  EfficiencyOpportunity,
  IncidentAnalytics,
  Report,
  ReportType,
  ReportCategory,
  ReportFormat,
  ReportSchedule,
  ReportFilters,
  ReportStatus,
  ChartConfiguration,
  ChartType,
  DataSource,
  AxisConfiguration,
  SeriesConfiguration,
  ChartStyling,
  ChartInteractions,
  TableConfiguration,
  TableColumn,
  TablePagination,
  TableSorting,
  TableFiltering,
  TableStyling,
  Alert,
  AlertType,
  AlertSeverity,
  AlertStatus,
  AlertCondition,
  AlertNotification,
  DataExport,
} from "./analytics/index";

export type {
  // API types
  ApiResponse,
  ApiError as APIError,
  ApiMeta,
  PaginatedResponse,
  SearchResponse as APISearchResponse,
  FacetResult,
  ApiConfig,
  RequestOptions,
  LoginRequest,
  LoginResponse as APILoginResponse,
  RefreshTokenRequest,
  RefreshTokenResponse,
  PasswordResetRequest as APIPasswordResetRequest,
  PasswordResetResponse,
  PasswordResetConfirmRequest,
  GetTowersRequest,
  CreateTowerRequest,
  UpdateTowerRequest,
  BulkTowerOperationRequest,
  BulkTowerOperationResponse,
  GetCoverageRequest,
  CoverageAnalysisRequest,
  CoverageAnalysisResponse,
  GetAnalyticsRequest,
  AnalyticsData,
  GetAnalyticsResponse,
  CreateReportRequest,
  GenerateReportRequest,
  GenerateReportResponse,
  ImportDataRequest,
  ImportDataResponse,
  ExportDataRequest,
  ExportDataResponse,
  WebSocketMessage,
  SubscriptionRequest,
  SubscriptionResponse,
  FileUploadRequest,
  FileUploadResponse,
  MultipartUploadRequest,
  MultipartUploadResponse,
  HealthCheckResponse,
  ServiceHealth,
  SystemMetricsResponse,
  RateLimitInfo,
  RateLimitResponse,
  WebhookConfig,
  WebhookPayload,
  WebhookDelivery,
  ApiEndpoint,
  ApiParameter,
  ApiRequestBody,
  ApiErrorDetails,
  ValidationErrorResponse,
  CacheConfig,
  CacheStrategy,
  CacheStats,
} from "./api/index";


