-- Migration: Clear old regions and seed Dark Fiber Customer Folders with Hierarchy
-- Date: 2026-04-27

BEGIN;

DELETE FROM dark_fiber_folders;

DO $$
DECLARE
  cust_id_0 INTEGER;
  cust_id_1 INTEGER;
  cust_id_2 INTEGER;
  cust_id_3 INTEGER;
  cust_id_4 INTEGER;
  cust_id_5 INTEGER;
  cust_id_6 INTEGER;
  cust_id_7 INTEGER;
  cust_id_8 INTEGER;
  cust_id_9 INTEGER;
  cust_id_10 INTEGER;
  cust_id_11 INTEGER;
  cust_id_12 INTEGER;
BEGIN

  INSERT INTO dark_fiber_folders (name) VALUES ('Airtel') RETURNING id INTO cust_id_0;
  INSERT INTO dark_fiber_folders (name, parent_id) VALUES 
  ('Andaman and Nicobar Islands', cust_id_0),
  ('Andhra Pradesh', cust_id_0),
  ('Arunachal Pradesh', cust_id_0),
  ('Assam', cust_id_0),
  ('Bihar', cust_id_0),
  ('Chandigarh', cust_id_0),
  ('Chhattisgarh', cust_id_0),
  ('Dadra and Nagar Haveli and Daman and Diu', cust_id_0),
  ('Delhi', cust_id_0),
  ('Goa', cust_id_0),
  ('Gujarat', cust_id_0),
  ('Haryana', cust_id_0),
  ('Himachal Pradesh', cust_id_0),
  ('Jammu and Kashmir', cust_id_0),
  ('Jharkhand', cust_id_0),
  ('Karnataka', cust_id_0),
  ('Kerala', cust_id_0),
  ('Ladakh', cust_id_0),
  ('Lakshadweep', cust_id_0),
  ('Madhya Pradesh', cust_id_0),
  ('Maharashtra', cust_id_0),
  ('Manipur', cust_id_0),
  ('Meghalaya', cust_id_0),
  ('Mizoram', cust_id_0),
  ('Nagaland', cust_id_0),
  ('Odisha', cust_id_0),
  ('Puducherry', cust_id_0),
  ('Punjab', cust_id_0),
  ('Rajasthan', cust_id_0),
  ('Sikkim', cust_id_0),
  ('Tamil Nadu', cust_id_0),
  ('Telangana', cust_id_0),
  ('Tripura', cust_id_0),
  ('Uttar Pradesh', cust_id_0),
  ('Uttarakhand', cust_id_0),
  ('West Bengal', cust_id_0);

  INSERT INTO dark_fiber_folders (name) VALUES ('BSNL') RETURNING id INTO cust_id_1;
  INSERT INTO dark_fiber_folders (name, parent_id) VALUES 
  ('Andaman and Nicobar Islands', cust_id_1),
  ('Andhra Pradesh', cust_id_1),
  ('Arunachal Pradesh', cust_id_1),
  ('Assam', cust_id_1),
  ('Bihar', cust_id_1),
  ('Chandigarh', cust_id_1),
  ('Chhattisgarh', cust_id_1),
  ('Dadra and Nagar Haveli and Daman and Diu', cust_id_1),
  ('Delhi', cust_id_1),
  ('Goa', cust_id_1),
  ('Gujarat', cust_id_1),
  ('Haryana', cust_id_1),
  ('Himachal Pradesh', cust_id_1),
  ('Jammu and Kashmir', cust_id_1),
  ('Jharkhand', cust_id_1),
  ('Karnataka', cust_id_1),
  ('Kerala', cust_id_1),
  ('Ladakh', cust_id_1),
  ('Lakshadweep', cust_id_1),
  ('Madhya Pradesh', cust_id_1),
  ('Maharashtra', cust_id_1),
  ('Manipur', cust_id_1),
  ('Meghalaya', cust_id_1),
  ('Mizoram', cust_id_1),
  ('Nagaland', cust_id_1),
  ('Odisha', cust_id_1),
  ('Puducherry', cust_id_1),
  ('Punjab', cust_id_1),
  ('Rajasthan', cust_id_1),
  ('Sikkim', cust_id_1),
  ('Tamil Nadu', cust_id_1),
  ('Telangana', cust_id_1),
  ('Tripura', cust_id_1),
  ('Uttar Pradesh', cust_id_1),
  ('Uttarakhand', cust_id_1),
  ('West Bengal', cust_id_1);

  INSERT INTO dark_fiber_folders (name) VALUES ('Jio') RETURNING id INTO cust_id_2;
  INSERT INTO dark_fiber_folders (name, parent_id) VALUES 
  ('Andaman and Nicobar Islands', cust_id_2),
  ('Andhra Pradesh', cust_id_2),
  ('Arunachal Pradesh', cust_id_2),
  ('Assam', cust_id_2),
  ('Bihar', cust_id_2),
  ('Chandigarh', cust_id_2),
  ('Chhattisgarh', cust_id_2),
  ('Dadra and Nagar Haveli and Daman and Diu', cust_id_2),
  ('Delhi', cust_id_2),
  ('Goa', cust_id_2),
  ('Gujarat', cust_id_2),
  ('Haryana', cust_id_2),
  ('Himachal Pradesh', cust_id_2),
  ('Jammu and Kashmir', cust_id_2),
  ('Jharkhand', cust_id_2),
  ('Karnataka', cust_id_2),
  ('Kerala', cust_id_2),
  ('Ladakh', cust_id_2),
  ('Lakshadweep', cust_id_2),
  ('Madhya Pradesh', cust_id_2),
  ('Maharashtra', cust_id_2),
  ('Manipur', cust_id_2),
  ('Meghalaya', cust_id_2),
  ('Mizoram', cust_id_2),
  ('Nagaland', cust_id_2),
  ('Odisha', cust_id_2),
  ('Puducherry', cust_id_2),
  ('Punjab', cust_id_2),
  ('Rajasthan', cust_id_2),
  ('Sikkim', cust_id_2),
  ('Tamil Nadu', cust_id_2),
  ('Telangana', cust_id_2),
  ('Tripura', cust_id_2),
  ('Uttar Pradesh', cust_id_2),
  ('Uttarakhand', cust_id_2),
  ('West Bengal', cust_id_2);

  INSERT INTO dark_fiber_folders (name) VALUES ('Sify') RETURNING id INTO cust_id_3;
  INSERT INTO dark_fiber_folders (name, parent_id) VALUES 
  ('Andaman and Nicobar Islands', cust_id_3),
  ('Andhra Pradesh', cust_id_3),
  ('Arunachal Pradesh', cust_id_3),
  ('Assam', cust_id_3),
  ('Bihar', cust_id_3),
  ('Chandigarh', cust_id_3),
  ('Chhattisgarh', cust_id_3),
  ('Dadra and Nagar Haveli and Daman and Diu', cust_id_3),
  ('Delhi', cust_id_3),
  ('Goa', cust_id_3),
  ('Gujarat', cust_id_3),
  ('Haryana', cust_id_3),
  ('Himachal Pradesh', cust_id_3),
  ('Jammu and Kashmir', cust_id_3),
  ('Jharkhand', cust_id_3),
  ('Karnataka', cust_id_3),
  ('Kerala', cust_id_3),
  ('Ladakh', cust_id_3),
  ('Lakshadweep', cust_id_3),
  ('Madhya Pradesh', cust_id_3),
  ('Maharashtra', cust_id_3),
  ('Manipur', cust_id_3),
  ('Meghalaya', cust_id_3),
  ('Mizoram', cust_id_3),
  ('Nagaland', cust_id_3),
  ('Odisha', cust_id_3),
  ('Puducherry', cust_id_3),
  ('Punjab', cust_id_3),
  ('Rajasthan', cust_id_3),
  ('Sikkim', cust_id_3),
  ('Tamil Nadu', cust_id_3),
  ('Telangana', cust_id_3),
  ('Tripura', cust_id_3),
  ('Uttar Pradesh', cust_id_3),
  ('Uttarakhand', cust_id_3),
  ('West Bengal', cust_id_3);

  INSERT INTO dark_fiber_folders (name) VALUES ('Tata') RETURNING id INTO cust_id_4;
  INSERT INTO dark_fiber_folders (name, parent_id) VALUES 
  ('Andaman and Nicobar Islands', cust_id_4),
  ('Andhra Pradesh', cust_id_4),
  ('Arunachal Pradesh', cust_id_4),
  ('Assam', cust_id_4),
  ('Bihar', cust_id_4),
  ('Chandigarh', cust_id_4),
  ('Chhattisgarh', cust_id_4),
  ('Dadra and Nagar Haveli and Daman and Diu', cust_id_4),
  ('Delhi', cust_id_4),
  ('Goa', cust_id_4),
  ('Gujarat', cust_id_4),
  ('Haryana', cust_id_4),
  ('Himachal Pradesh', cust_id_4),
  ('Jammu and Kashmir', cust_id_4),
  ('Jharkhand', cust_id_4),
  ('Karnataka', cust_id_4),
  ('Kerala', cust_id_4),
  ('Ladakh', cust_id_4),
  ('Lakshadweep', cust_id_4),
  ('Madhya Pradesh', cust_id_4),
  ('Maharashtra', cust_id_4),
  ('Manipur', cust_id_4),
  ('Meghalaya', cust_id_4),
  ('Mizoram', cust_id_4),
  ('Nagaland', cust_id_4),
  ('Odisha', cust_id_4),
  ('Puducherry', cust_id_4),
  ('Punjab', cust_id_4),
  ('Rajasthan', cust_id_4),
  ('Sikkim', cust_id_4),
  ('Tamil Nadu', cust_id_4),
  ('Telangana', cust_id_4),
  ('Tripura', cust_id_4),
  ('Uttar Pradesh', cust_id_4),
  ('Uttarakhand', cust_id_4),
  ('West Bengal', cust_id_4);

  INSERT INTO dark_fiber_folders (name) VALUES ('Vodafone') RETURNING id INTO cust_id_5;
  INSERT INTO dark_fiber_folders (name, parent_id) VALUES 
  ('Andaman and Nicobar Islands', cust_id_5),
  ('Andhra Pradesh', cust_id_5),
  ('Arunachal Pradesh', cust_id_5),
  ('Assam', cust_id_5),
  ('Bihar', cust_id_5),
  ('Chandigarh', cust_id_5),
  ('Chhattisgarh', cust_id_5),
  ('Dadra and Nagar Haveli and Daman and Diu', cust_id_5),
  ('Delhi', cust_id_5),
  ('Goa', cust_id_5),
  ('Gujarat', cust_id_5),
  ('Haryana', cust_id_5),
  ('Himachal Pradesh', cust_id_5),
  ('Jammu and Kashmir', cust_id_5),
  ('Jharkhand', cust_id_5),
  ('Karnataka', cust_id_5),
  ('Kerala', cust_id_5),
  ('Ladakh', cust_id_5),
  ('Lakshadweep', cust_id_5),
  ('Madhya Pradesh', cust_id_5),
  ('Maharashtra', cust_id_5),
  ('Manipur', cust_id_5),
  ('Meghalaya', cust_id_5),
  ('Mizoram', cust_id_5),
  ('Nagaland', cust_id_5),
  ('Odisha', cust_id_5),
  ('Puducherry', cust_id_5),
  ('Punjab', cust_id_5),
  ('Rajasthan', cust_id_5),
  ('Sikkim', cust_id_5),
  ('Tamil Nadu', cust_id_5),
  ('Telangana', cust_id_5),
  ('Tripura', cust_id_5),
  ('Uttar Pradesh', cust_id_5),
  ('Uttarakhand', cust_id_5),
  ('West Bengal', cust_id_5);

  INSERT INTO dark_fiber_folders (name) VALUES ('Dark Fiber') RETURNING id INTO cust_id_6;
  INSERT INTO dark_fiber_folders (name, parent_id) VALUES 
  ('Andaman and Nicobar Islands', cust_id_6),
  ('Andhra Pradesh', cust_id_6),
  ('Arunachal Pradesh', cust_id_6),
  ('Assam', cust_id_6),
  ('Bihar', cust_id_6),
  ('Chandigarh', cust_id_6),
  ('Chhattisgarh', cust_id_6),
  ('Dadra and Nagar Haveli and Daman and Diu', cust_id_6),
  ('Delhi', cust_id_6),
  ('Goa', cust_id_6),
  ('Gujarat', cust_id_6),
  ('Haryana', cust_id_6),
  ('Himachal Pradesh', cust_id_6),
  ('Jammu and Kashmir', cust_id_6),
  ('Jharkhand', cust_id_6),
  ('Karnataka', cust_id_6),
  ('Kerala', cust_id_6),
  ('Ladakh', cust_id_6),
  ('Lakshadweep', cust_id_6),
  ('Madhya Pradesh', cust_id_6),
  ('Maharashtra', cust_id_6),
  ('Manipur', cust_id_6),
  ('Meghalaya', cust_id_6),
  ('Mizoram', cust_id_6),
  ('Nagaland', cust_id_6),
  ('Odisha', cust_id_6),
  ('Puducherry', cust_id_6),
  ('Punjab', cust_id_6),
  ('Rajasthan', cust_id_6),
  ('Sikkim', cust_id_6),
  ('Tamil Nadu', cust_id_6),
  ('Telangana', cust_id_6),
  ('Tripura', cust_id_6),
  ('Uttar Pradesh', cust_id_6),
  ('Uttarakhand', cust_id_6),
  ('West Bengal', cust_id_6);

  INSERT INTO dark_fiber_folders (name) VALUES ('JTM Internet') RETURNING id INTO cust_id_7;
  INSERT INTO dark_fiber_folders (name, parent_id) VALUES 
  ('Andaman and Nicobar Islands', cust_id_7),
  ('Andhra Pradesh', cust_id_7),
  ('Arunachal Pradesh', cust_id_7),
  ('Assam', cust_id_7),
  ('Bihar', cust_id_7),
  ('Chandigarh', cust_id_7),
  ('Chhattisgarh', cust_id_7),
  ('Dadra and Nagar Haveli and Daman and Diu', cust_id_7),
  ('Delhi', cust_id_7),
  ('Goa', cust_id_7),
  ('Gujarat', cust_id_7),
  ('Haryana', cust_id_7),
  ('Himachal Pradesh', cust_id_7),
  ('Jammu and Kashmir', cust_id_7),
  ('Jharkhand', cust_id_7),
  ('Karnataka', cust_id_7),
  ('Kerala', cust_id_7),
  ('Ladakh', cust_id_7),
  ('Lakshadweep', cust_id_7),
  ('Madhya Pradesh', cust_id_7),
  ('Maharashtra', cust_id_7),
  ('Manipur', cust_id_7),
  ('Meghalaya', cust_id_7),
  ('Mizoram', cust_id_7),
  ('Nagaland', cust_id_7),
  ('Odisha', cust_id_7),
  ('Puducherry', cust_id_7),
  ('Punjab', cust_id_7),
  ('Rajasthan', cust_id_7),
  ('Sikkim', cust_id_7),
  ('Tamil Nadu', cust_id_7),
  ('Telangana', cust_id_7),
  ('Tripura', cust_id_7),
  ('Uttar Pradesh', cust_id_7),
  ('Uttarakhand', cust_id_7),
  ('West Bengal', cust_id_7);

  INSERT INTO dark_fiber_folders (name) VALUES ('Optimal Telemedia') RETURNING id INTO cust_id_8;
  INSERT INTO dark_fiber_folders (name, parent_id) VALUES 
  ('Andaman and Nicobar Islands', cust_id_8),
  ('Andhra Pradesh', cust_id_8),
  ('Arunachal Pradesh', cust_id_8),
  ('Assam', cust_id_8),
  ('Bihar', cust_id_8),
  ('Chandigarh', cust_id_8),
  ('Chhattisgarh', cust_id_8),
  ('Dadra and Nagar Haveli and Daman and Diu', cust_id_8),
  ('Delhi', cust_id_8),
  ('Goa', cust_id_8),
  ('Gujarat', cust_id_8),
  ('Haryana', cust_id_8),
  ('Himachal Pradesh', cust_id_8),
  ('Jammu and Kashmir', cust_id_8),
  ('Jharkhand', cust_id_8),
  ('Karnataka', cust_id_8),
  ('Kerala', cust_id_8),
  ('Ladakh', cust_id_8),
  ('Lakshadweep', cust_id_8),
  ('Madhya Pradesh', cust_id_8),
  ('Maharashtra', cust_id_8),
  ('Manipur', cust_id_8),
  ('Meghalaya', cust_id_8),
  ('Mizoram', cust_id_8),
  ('Nagaland', cust_id_8),
  ('Odisha', cust_id_8),
  ('Puducherry', cust_id_8),
  ('Punjab', cust_id_8),
  ('Rajasthan', cust_id_8),
  ('Sikkim', cust_id_8),
  ('Tamil Nadu', cust_id_8),
  ('Telangana', cust_id_8),
  ('Tripura', cust_id_8),
  ('Uttar Pradesh', cust_id_8),
  ('Uttarakhand', cust_id_8),
  ('West Bengal', cust_id_8);

  INSERT INTO dark_fiber_folders (name) VALUES ('PGCIL') RETURNING id INTO cust_id_9;
  INSERT INTO dark_fiber_folders (name, parent_id) VALUES 
  ('Andaman and Nicobar Islands', cust_id_9),
  ('Andhra Pradesh', cust_id_9),
  ('Arunachal Pradesh', cust_id_9),
  ('Assam', cust_id_9),
  ('Bihar', cust_id_9),
  ('Chandigarh', cust_id_9),
  ('Chhattisgarh', cust_id_9),
  ('Dadra and Nagar Haveli and Daman and Diu', cust_id_9),
  ('Delhi', cust_id_9),
  ('Goa', cust_id_9),
  ('Gujarat', cust_id_9),
  ('Haryana', cust_id_9),
  ('Himachal Pradesh', cust_id_9),
  ('Jammu and Kashmir', cust_id_9),
  ('Jharkhand', cust_id_9),
  ('Karnataka', cust_id_9),
  ('Kerala', cust_id_9),
  ('Ladakh', cust_id_9),
  ('Lakshadweep', cust_id_9),
  ('Madhya Pradesh', cust_id_9),
  ('Maharashtra', cust_id_9),
  ('Manipur', cust_id_9),
  ('Meghalaya', cust_id_9),
  ('Mizoram', cust_id_9),
  ('Nagaland', cust_id_9),
  ('Odisha', cust_id_9),
  ('Puducherry', cust_id_9),
  ('Punjab', cust_id_9),
  ('Rajasthan', cust_id_9),
  ('Sikkim', cust_id_9),
  ('Tamil Nadu', cust_id_9),
  ('Telangana', cust_id_9),
  ('Tripura', cust_id_9),
  ('Uttar Pradesh', cust_id_9),
  ('Uttarakhand', cust_id_9),
  ('West Bengal', cust_id_9);

  INSERT INTO dark_fiber_folders (name) VALUES ('Railtel') RETURNING id INTO cust_id_10;
  INSERT INTO dark_fiber_folders (name, parent_id) VALUES 
  ('Andaman and Nicobar Islands', cust_id_10),
  ('Andhra Pradesh', cust_id_10),
  ('Arunachal Pradesh', cust_id_10),
  ('Assam', cust_id_10),
  ('Bihar', cust_id_10),
  ('Chandigarh', cust_id_10),
  ('Chhattisgarh', cust_id_10),
  ('Dadra and Nagar Haveli and Daman and Diu', cust_id_10),
  ('Delhi', cust_id_10),
  ('Goa', cust_id_10),
  ('Gujarat', cust_id_10),
  ('Haryana', cust_id_10),
  ('Himachal Pradesh', cust_id_10),
  ('Jammu and Kashmir', cust_id_10),
  ('Jharkhand', cust_id_10),
  ('Karnataka', cust_id_10),
  ('Kerala', cust_id_10),
  ('Ladakh', cust_id_10),
  ('Lakshadweep', cust_id_10),
  ('Madhya Pradesh', cust_id_10),
  ('Maharashtra', cust_id_10),
  ('Manipur', cust_id_10),
  ('Meghalaya', cust_id_10),
  ('Mizoram', cust_id_10),
  ('Nagaland', cust_id_10),
  ('Odisha', cust_id_10),
  ('Puducherry', cust_id_10),
  ('Punjab', cust_id_10),
  ('Rajasthan', cust_id_10),
  ('Sikkim', cust_id_10),
  ('Tamil Nadu', cust_id_10),
  ('Telangana', cust_id_10),
  ('Tripura', cust_id_10),
  ('Uttar Pradesh', cust_id_10),
  ('Uttarakhand', cust_id_10),
  ('West Bengal', cust_id_10);

  INSERT INTO dark_fiber_folders (name) VALUES ('RCOM') RETURNING id INTO cust_id_11;
  INSERT INTO dark_fiber_folders (name, parent_id) VALUES 
  ('Andaman and Nicobar Islands', cust_id_11),
  ('Andhra Pradesh', cust_id_11),
  ('Arunachal Pradesh', cust_id_11),
  ('Assam', cust_id_11),
  ('Bihar', cust_id_11),
  ('Chandigarh', cust_id_11),
  ('Chhattisgarh', cust_id_11),
  ('Dadra and Nagar Haveli and Daman and Diu', cust_id_11),
  ('Delhi', cust_id_11),
  ('Goa', cust_id_11),
  ('Gujarat', cust_id_11),
  ('Haryana', cust_id_11),
  ('Himachal Pradesh', cust_id_11),
  ('Jammu and Kashmir', cust_id_11),
  ('Jharkhand', cust_id_11),
  ('Karnataka', cust_id_11),
  ('Kerala', cust_id_11),
  ('Ladakh', cust_id_11),
  ('Lakshadweep', cust_id_11),
  ('Madhya Pradesh', cust_id_11),
  ('Maharashtra', cust_id_11),
  ('Manipur', cust_id_11),
  ('Meghalaya', cust_id_11),
  ('Mizoram', cust_id_11),
  ('Nagaland', cust_id_11),
  ('Odisha', cust_id_11),
  ('Puducherry', cust_id_11),
  ('Punjab', cust_id_11),
  ('Rajasthan', cust_id_11),
  ('Sikkim', cust_id_11),
  ('Tamil Nadu', cust_id_11),
  ('Telangana', cust_id_11),
  ('Tripura', cust_id_11),
  ('Uttar Pradesh', cust_id_11),
  ('Uttarakhand', cust_id_11),
  ('West Bengal', cust_id_11);

  INSERT INTO dark_fiber_folders (name) VALUES ('TTSL') RETURNING id INTO cust_id_12;
  INSERT INTO dark_fiber_folders (name, parent_id) VALUES 
  ('Andaman and Nicobar Islands', cust_id_12),
  ('Andhra Pradesh', cust_id_12),
  ('Arunachal Pradesh', cust_id_12),
  ('Assam', cust_id_12),
  ('Bihar', cust_id_12),
  ('Chandigarh', cust_id_12),
  ('Chhattisgarh', cust_id_12),
  ('Dadra and Nagar Haveli and Daman and Diu', cust_id_12),
  ('Delhi', cust_id_12),
  ('Goa', cust_id_12),
  ('Gujarat', cust_id_12),
  ('Haryana', cust_id_12),
  ('Himachal Pradesh', cust_id_12),
  ('Jammu and Kashmir', cust_id_12),
  ('Jharkhand', cust_id_12),
  ('Karnataka', cust_id_12),
  ('Kerala', cust_id_12),
  ('Ladakh', cust_id_12),
  ('Lakshadweep', cust_id_12),
  ('Madhya Pradesh', cust_id_12),
  ('Maharashtra', cust_id_12),
  ('Manipur', cust_id_12),
  ('Meghalaya', cust_id_12),
  ('Mizoram', cust_id_12),
  ('Nagaland', cust_id_12),
  ('Odisha', cust_id_12),
  ('Puducherry', cust_id_12),
  ('Punjab', cust_id_12),
  ('Rajasthan', cust_id_12),
  ('Sikkim', cust_id_12),
  ('Tamil Nadu', cust_id_12),
  ('Telangana', cust_id_12),
  ('Tripura', cust_id_12),
  ('Uttar Pradesh', cust_id_12),
  ('Uttarakhand', cust_id_12),
  ('West Bengal', cust_id_12);

END $$;

COMMIT;
