-- Migration: System Updates / News & Platform Release Notes
-- Date: 2026-04-08
-- Description:
--   Creates the `system_updates` table to store platform release notes,
--   announcements, and automated version-bump notifications.
--   Includes an auto-update trigger on `updated_at` and performance indexes.

-- =============================================================================
-- 1. Enable uuid-ossp extension (idempotent)
-- =============================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- 2. Create the system_updates table
-- =============================================================================
CREATE TABLE IF NOT EXISTS system_updates (
    id           UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
    title        VARCHAR(255) NOT NULL,
    content      TEXT         NOT NULL,
    type         VARCHAR(50)  NOT NULL
                   CHECK (type IN ('feature', 'bugfix', 'maintenance', 'security', 'announcement', 'auto-release')),
    version_tag  VARCHAR(50),                          -- e.g. "1.4.2" (nullable for manual announcements)
    is_published BOOLEAN      NOT NULL DEFAULT FALSE,  -- FALSE = draft, TRUE = visible to users
    is_automated BOOLEAN      NOT NULL DEFAULT FALSE,  -- TRUE = generated by version-bump detection
    created_by   INTEGER      REFERENCES users(id) ON DELETE SET NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 3. Auto-update trigger for updated_at
-- =============================================================================

-- Create the trigger function (idempotent via OR REPLACE)
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach trigger to system_updates (drop first to make idempotent)
DROP TRIGGER IF EXISTS set_system_updates_updated_at ON system_updates;

CREATE TRIGGER set_system_updates_updated_at
    BEFORE UPDATE ON system_updates
    FOR EACH ROW
    EXECUTE PROCEDURE trigger_set_updated_at();

-- =============================================================================
-- 4. Indexes for common query patterns
-- =============================================================================

-- Index: quickly fetch only published updates (used by user-facing panel)
CREATE INDEX IF NOT EXISTS idx_system_updates_published
    ON system_updates (is_published, created_at DESC);

-- Index: filter by type (e.g. only "feature" updates)
CREATE INDEX IF NOT EXISTS idx_system_updates_type
    ON system_updates (type);

-- Index: find updates for a specific version tag
CREATE INDEX IF NOT EXISTS idx_system_updates_version_tag
    ON system_updates (version_tag)
    WHERE version_tag IS NOT NULL;

-- =============================================================================
-- 5. Done
-- =============================================================================
-- Run this file once against your PostgreSQL database:
--   psql -U <user> -d <database> -f 20260408_system_updates.sql
--
-- The `IF NOT EXISTS` / `OR REPLACE` / `ON CONFLICT` guards make it safe
-- to re-run without destroying existing data.
