import { PermissionCategory } from "../permissionsEnums";
import type { PermissionDefinition } from "../permissionsModels";

export const ADMIN_PERMISSIONS: PermissionDefinition[] = [
  {
    id: "admin:view",
    name: "View Admin Panel",
    description: "Access the Administration section",
    category: PermissionCategory.ADMIN,
    module: "admin",
    action: "view",
    isSystemPermission: true,
  },
  {
    id: "admin:audit_logs",
    name: "View Audit Logs",
    description: "View system audit logs",
    category: PermissionCategory.ADMIN,
    module: "audit_logs",
    action: "view",
    isSystemPermission: true,
  },
  {
    id: "admin:audit_logs:export",
    name: "Export Audit Logs",
    description: "Export audit logs to CSV",
    category: PermissionCategory.ADMIN,
    module: "audit_logs",
    action: "export",
    isSystemPermission: true,
  },
  {
    id: "admin:audit_logs:clear",
    name: "Clear All Audit Logs",
    description: "Delete all audit logs (Action is logged)",
    category: PermissionCategory.ADMIN,
    module: "audit_logs",
    action: "clear",
    isSystemPermission: true,
  },
  // Other existing admin permissions used in UI
  {
    id: "admin:region_request",
    name: "Region Requests",
    description: "Manage region access requests",
    category: PermissionCategory.ADMIN,
    module: "admin",
    action: "region_request",
    isSystemPermission: true,
  },
  {
    id: "admin:bulk_assignment",
    name: "Bulk Assignment",
    description: "Perform bulk assignments",
    category: PermissionCategory.ADMIN,
    module: "admin",
    action: "bulk_assignment",
    isSystemPermission: true,
  },
  {
    id: "admin:temp_access",
    name: "Temporary Access",
    description: "Manage temporary access requests",
    category: PermissionCategory.ADMIN,
    module: "admin",
    action: "temp_access",
    isSystemPermission: true,
  },
  {
    id: "admin:permissions:manage",
    name: "Manage Permissions",
    description: "Create, update, and delete system permissions",
    category: PermissionCategory.ADMIN,
    module: "permissions",
    action: "manage",
    isSystemPermission: true,
  },
  {
    id: "admin:temp_access:grant",
    name: "Grant Temporary Access",
    description: "Grant temporary region access to users",
    category: PermissionCategory.ADMIN,
    module: "temp_access",
    action: "grant",
    isSystemPermission: true,
  },
  {
    id: "admin:temp_access:revoke",
    name: "Revoke Temporary Access",
    description: "Revoke temporary region access from users",
    category: PermissionCategory.ADMIN,
    module: "temp_access",
    action: "revoke",
    isSystemPermission: true,
  },
  {
    id: "admin:export_reports",
    name: "Export Reports",
    description: "Export system reports",
    category: PermissionCategory.ADMIN,
    module: "admin",
    action: "export_reports",
    isSystemPermission: true,
  },
  {
    id: "admin:password_reset",
    name: "Password Reset Requests",
    description: "Manage password reset requests",
    category: PermissionCategory.ADMIN,
    module: "admin",
    action: "password_reset",
    isSystemPermission: true,
  },
  {
    id: "admin:region_boundaries",
    name: "Region Boundaries",
    description: "Manage region boundaries",
    category: PermissionCategory.ADMIN,
    module: "admin",
    action: "region_boundaries",
    isSystemPermission: true,
  },
  {
    id: "admin:database",
    name: "Database Management",
    description: "Access database management tools",
    category: PermissionCategory.ADMIN,
    module: "admin",
    action: "database",
    isSystemPermission: true,
  },
  {
    id: "admin:database:export",
    name: "Targeted Database Export",
    description: "Export specific database tables with/without data",
    category: PermissionCategory.ADMIN,
    module: "admin",
    action: "database_export",
    isSystemPermission: true,
  },
  {
    id: "admin:role_builder",
    name: "Role Builder",
    description: "Create and manage custom roles with permissions",
    category: PermissionCategory.ADMIN,
    module: "admin",
    action: "role_builder",
    isSystemPermission: true,
  },
  {
    id: "admin:system_updates",
    name: "System Updates",
    description: "Manage and deploy system updates",
    category: PermissionCategory.ADMIN,
    module: "admin",
    action: "system_updates",
    isSystemPermission: true,
  },
];

