import { PermissionCategory } from "../permissionsEnums";
import type { PermissionDefinition } from "../permissionsModels";

export const GIS_TOOL_PERMISSIONS: PermissionDefinition[] = [
  // ===== GIS Tools =====
  {
    id: "map:tools:distance",
    name: "Use Distance Tool",
    description: "Allows user to use the distance measurement tool",
    category: PermissionCategory.GIS_TOOLS,
    module: "distance",
    action: "use",
    isSystemPermission: true,
  },
  {
    id: "map:tools:distance:save",
    name: "Save Distance Measurements",
    description: "Allows user to save distance measurements",
    category: PermissionCategory.GIS_TOOLS,
    module: "distance",
    action: "save",
    isSystemPermission: true,
  },
  {
    id: "map:tools:distance:delete:own",
    name: "Delete Own Distance Measurements",
    description: "Allows user to delete their own distance measurements",
    category: PermissionCategory.GIS_TOOLS,
    module: "distance",
    action: "delete.own",
    isSystemPermission: true,
  },
  {
    id: "map:tools:distance:delete:any",
    name: "Delete Any Distance Measurements",
    description: "Allows user to delete any distance measurement",
    category: PermissionCategory.GIS_TOOLS,
    module: "distance",
    action: "delete.any",
    isSystemPermission: true,
  },
  {
    id: "map:tools:polygon",
    name: "Use Polygon Tool",
    description: "Allows user to use the polygon drawing tool",
    category: PermissionCategory.GIS_TOOLS,
    module: "polygon",
    action: "use",
    isSystemPermission: true,
  },
  {
    id: "map:tools:polygon:save",
    name: "Save Polygons",
    description: "Allows user to save polygons",
    category: PermissionCategory.GIS_TOOLS,
    module: "polygon",
    action: "save",
    isSystemPermission: true,
  },
  {
    id: "map:tools:polygon:delete:own",
    name: "Delete Own Polygons",
    description: "Allows user to delete their own polygons",
    category: PermissionCategory.GIS_TOOLS,
    module: "polygon",
    action: "delete.own",
    isSystemPermission: true,
  },
  {
    id: "map:tools:polygon:delete:any",
    name: "Delete Any Polygons",
    description: "Allows user to delete any polygon",
    category: PermissionCategory.GIS_TOOLS,
    module: "polygon",
    action: "delete.any",
    isSystemPermission: true,
  },
  {
    id: "map:tools:circle",
    name: "Use Circle Tool",
    description: "Allows user to use the circle/radius tool",
    category: PermissionCategory.GIS_TOOLS,
    module: "circle",
    action: "use",
    isSystemPermission: true,
  },
  {
    id: "map:tools:circle:save",
    name: "Save Circles",
    description: "Allows user to save circles",
    category: PermissionCategory.GIS_TOOLS,
    module: "circle",
    action: "save",
    isSystemPermission: true,
  },
  {
    id: "map:tools:circle:delete:own",
    name: "Delete Own Circles",
    description: "Allows user to delete their own circles",
    category: PermissionCategory.GIS_TOOLS,
    module: "circle",
    action: "delete.own",
    isSystemPermission: true,
  },
  {
    id: "map:tools:circle:delete:any",
    name: "Delete Any Circles",
    description: "Allows user to delete any circle",
    category: PermissionCategory.GIS_TOOLS,
    module: "circle",
    action: "delete.any",
    isSystemPermission: true,
  },
  {
    id: "map:tools:elevation",
    name: "Use Elevation Tool",
    description: "Allows user to use the elevation profile tool",
    category: PermissionCategory.GIS_TOOLS,
    module: "elevation",
    action: "use",
    isSystemPermission: true,
  },
  {
    id: "map:tools:elevation:save",
    name: "Save Elevation Profiles",
    description: "Allows user to save elevation profiles",
    category: PermissionCategory.GIS_TOOLS,
    module: "elevation",
    action: "save",
    isSystemPermission: true,
  },
  {
    id: "map:tools:elevation:delete:own",
    name: "Delete Own Elevation Profiles",
    description: "Allows user to delete their own elevation profiles",
    category: PermissionCategory.GIS_TOOLS,
    module: "elevation",
    action: "delete.own",
    isSystemPermission: true,
  },
  {
    id: "map:tools:elevation:delete:any",
    name: "Delete Any Elevation Profiles",
    description: "Allows user to delete any elevation profile",
    category: PermissionCategory.GIS_TOOLS,
    module: "elevation",
    action: "delete.any",
    isSystemPermission: true,
  },
  {
    id: "map:tools:sector_rf",
    name: "Sector RF Coverage",
    description: "Allows user to use Sector RF tool",
    category: PermissionCategory.GIS_TOOLS,
    module: "sector_rf",
    action: "use",
    isSystemPermission: true,
  },
  {
    id: "converter:view",
    name: "View Converters Tab",
    description: "Allows access to the Converters tools",
    category: PermissionCategory.GIS_TOOLS, // Or create a new category enum if possible, but existing is safer
    module: "converter",
    action: "view",
    isSystemPermission: true,
  },
  {
    id: "converter:excel_to_kml",
    name: "Excel to KML Converter",
    description: "Use the Excel to KML/KMZ conversion tool",
    category: PermissionCategory.GIS_TOOLS,
    module: "converter",
    action: "use",
    isSystemPermission: true,
  },
];


