import { Step } from './types';

// Steps 6-10: Results and Advanced Features
export const stepsSecondHalf: Step[] = [
  {
    id: 6,
    title: "View Search Results",
    icon: "📋",
    color: "pink",
    action: "Review the list of search results",
    result: "Scrollable list shows all matching items with details",
    details: [
      "Result Display:",
      "  • Results counter: \"Results (15)\"",
      "  • Scrollable list (max height 320px)",
      "  • Each result shows:",
      "    - Icon based on source (📍 Places, 🎯 Coordinates, 💾 Saved)",
      "    - Name/title",
      "    - Address (if available)",
      "    - Distance (for saved data)",
      "    - Special badges (elevation, LOS)",
      "",
      "Result Icons:",
      "  • 📍 - Place search result",
      "  • 🎯 - Coordinate search result",
      "  • 💾 - Saved data result",
      "",
      "For Saved Data Results:",
      "  • Infrastructure: Item type, location, properties",
      "  • Distance: Total distance, elevation stats",
      "  • Elevation: LOS status, max/min elevation, bearing",
      "  • Polygon: Area, vertices count",
      "  • Circle: Radius, area",
      "  • Sector RF: Azimuth, beamwidth, radius"
    ]
  },
  {
    id: 7,
    title: "Select a Result",
    icon: "👆",
    color: "indigo",
    action: "Click on any search result",
    result: "Map navigates to location and displays the item",
    details: [
      "For Place/Coordinate Results:",
      "  • Map pans to location",
      "  • Zoom level set to 15",
      "  • Marker appears at location",
      "  • Info window opens with details",
      "  • Bookmark button available (⭐ Bookmark)",
      "",
      "For Saved Data Results:",
      "  • Map shows the selected item with details",
      "  • Details modal opens automatically",
      "  • Visual overlay created on map:",
      "    - Infrastructure: Custom marker (POP/SubPOP differentiation)",
      "    - Distance: Red polyline with A/B markers",
      "    - Elevation: Brown polyline with lettered markers (A, B, C...)",
      "    - Polygon: Colored polygon with border",
      "    - Circle: Circle with center marker",
      "    - Sector RF: Wedge-shaped coverage area",
      "",
      "Map Actions:",
      "  • Map automatically adjusts to show entire feature",
      "  • Previous overlays cleared",
      "  • Search panel remains open"
    ]
  },
  {
    id: 8,
    title: "Bookmarks",
    icon: "⭐",
    color: "yellow",
    action: "Save and manage favorite locations",
    result: "Quick access to frequently used locations",
    details: [
      "Open Bookmarks:",
      "  • Click ⭐ (star) icon in search panel header",
      "  • Toggles bookmark list view",
      "",
      "Bookmark Display:",
      "  • Shows count: \"⭐ Saved Bookmarks (5 total)\"",
      "  • Each bookmark shows:",
      "    - Name with yellow star icon",
      "    - Description",
      "    - Category badge",
      "    - Coordinates (lat, lng)",
      "    - Creation date",
      "",
      "Create Bookmark:",
      "  • Search for a place/coordinate",
      "  • Click result to show info window",
      "  • Click \"⭐ Bookmark\" button",
      "  • Success message appears",
      "",
      "Use Bookmark:",
      "  • Click any bookmark in the list",
      "  • Map navigates to location",
      "  • Marker and visualization appear",
      "",
      "Delete Bookmark:",
      "  • Right-click bookmark marker on map",
      "  • Confirm deletion",
      "  • Success message appears"
    ]
  },
  {
    id: 9,
    title: "Search History",
    icon: "🕐",
    color: "red",
    action: "View and reuse previous searches",
    result: "Quick access to recent search queries",
    details: [
      "View History:",
      "  • Click 🕐 (clock) icon in search panel",
      "  • Shows up to 5 most recent searches",
      "  • Appears when input field is focused",
      "",
      "History Display:",
      "  • \"Recent Searches\" header",
      "  • Each entry shows:",
      "    - Query text",
      "    - Number of results found",
      "    - Timestamp",
      "",
      "Reuse Search:",
      "  • Click any history entry",
      "  • Query fills input field",
      "  • Search executes automatically",
      "  • Results populate",
      "",
      "History Features:",
      "  • Automatically saved for quick access",
      "  • Persists across sessions",
      "  • Only successful searches saved",
      "",
      "Note: History is user-specific and private"
    ]
  },
  {
    id: 10,
    title: "Clear & Close",
    icon: "✖️",
    color: "gray",
    action: "Clear search or close panel",
    result: "Reset search state or hide search panel",
    details: [
      "Clear Search (X button next to input):",
      "  • Clears query text",
      "  • Removes results",
      "  • Panel stays open",
      "  • Keeps search type selection",
      "",
      "Clear Map Overlays (🗑️ Trash icon):",
      "  • Only visible when overlays exist on map",
      "  • Removes all search result markers/shapes",
      "  • Clears polylines, polygons, circles",
      "  • Closes info windows",
      "  • Does not close search panel",
      "",
      "Close Panel (X button in header):",
      "  • Closes search panel completely",
      "  • Clears query and results",
      "  • Hides history/bookmarks view",
      "  • Overlays remain on map (not cleared)",
      "",
      "Keyboard Shortcuts:",
      "  • ESC key - Close search panel",
      "  • ENTER key - Execute search",
      "  • Click outside panel - Close panel"
    ]
  }
];

// Pro tips data
export const proTips = [
  { title: "Quick Search", content: "Type at least 2 characters to trigger automatic search as you type." },
  { title: "Coordinate Formats", content: "Accepts multiple formats - decimal, degrees with symbols, comma or space separated." },
  { title: "User Filter", content: "Admin/Manager can search any user's saved data for comparison and analysis." },
  { title: "Elevation Filter", content: "Use checkbox to find only distance measurements with elevation data and LOS analysis." },
  { title: "Search History", content: "All searches automatically saved for quick reuse across sessions." },
  { title: "Bookmarks", content: "Save frequently accessed locations for instant navigation without searching again." },
];

