import { Step } from './types';

// Steps 7-12: GIS Data Hub to Analytics
export const stepsSecondHalf: Step[] = [
  {
    id: 7,
    title: "GIS Data Hub",
    icon: "🗂️",
    color: "indigo",
    action: "Manage all GIS data imports, exports, and saved items",
    result: "Centralized data management interface",
    details: [
      "Import Section:",
      "• Support for KML, CSV, Excel files",
      "• Drag & drop file upload",
      "• Preview before import",
      "• Bulk validation and processing",
      "• Error reporting for invalid data",
      "Export Section:",
      "• Export to KML, CSV, Excel, PDF",
      "• Filter data before export",
      "• Choose specific layers/types",
      "• Batch export multiple datasets",
      "My Data View:",
      "• All your saved items organized by type",
      "• Distance Measurements, Polygons, Circles",
      "• Infrastructure items, Elevation data",
      "• RF Sectors, Imported datasets",
      "Admin View (Admin only):",
      "• View all users' data",
      "• Filter by user, date, type",
      "• Bulk operations on any data",
      "Recent Imports History:",
      "• Timeline of recent imports",
      "• File names, dates, status",
      "Data Statistics:",
      "• Total items count",
      "• Storage usage",
      "• Items by type breakdown"
    ]
  },
  {
    id: 8,
    title: "Dashboard",
    icon: "📈",
    color: "cyan",
    action: "View KPIs, statistics, and system health",
    result: "Real-time overview of infrastructure and system metrics",
    details: [
      "9 KPI Cards showing:",
      "• Total Infrastructure count",
      "• POP sites count",
      "• Sub POP sites count",
      "• Tower count",
      "• Customer sites count",
      "• Active users count",
      "• Recent imports (30 days)",
      "• Data exports (30 days)",
      "• System uptime percentage",
      "Recent Activity Feed:",
      "• Real-time activity stream",
      "• User actions and changes",
      "• Auto-refreshes every 60 seconds",
      "• Filterable by user/action type",
      "Quick Actions (5 buttons):",
      "• Add New Inventory",
      "• Import Data",
      "• Export Report",
      "• View Map",
      "• Manage Users",
      "System Health Indicator:",
      "• Application performance status",
      "• Connection quality",
      "• Real-time sync status",
      "• Storage space available"
    ]
  },
  {
    id: 9,
    title: "Users Management",
    icon: "👥",
    color: "pink",
    action: "Manage user accounts, roles, and permissions (Admin/Manager)",
    result: "Complete user lifecycle management",
    details: [
      "User CRUD Operations:",
      "• Create new user accounts",
      "• Edit user information",
      "• Delete or deactivate users",
      "• View user details",
      "Role Assignment:",
      "• Assign roles: Admin, Manager, Technician, Viewer",
      "• Role change requires confirmation",
      "• Audit trail of role changes",
      "Region Assignment:",
      "• Assign users to specific states/regions",
      "• Multi-select region assignment",
      "• Bulk region updates",
      "User Activation/Deactivation:",
      "• Toggle user active status",
      "• Deactivated users cannot login",
      "• Reactivation available",
      "Session Management:",
      "• View active sessions",
      "• Force logout option",
      "• Session expiry settings",
      "Activity Tracking:",
      "• Last login timestamp",
      "• Recent actions history",
      "• Login location tracking",
      "Bulk Operations:",
      "• Select multiple users",
      "• Bulk role assignment",
      "• Bulk region updates",
      "• Bulk activation/deactivation"
    ]
  },
  {
    id: 10,
    title: "Groups Management",
    icon: "👥",
    color: "violet",
    action: "Create and manage user groups with shared permissions",
    result: "Organized team structure with group-based access",
    details: [
      "Group Creation:",
      "• Define group name and description",
      "• Set group permissions",
      "• Assign group leader/manager",
      "Member Management:",
      "• Add users to groups",
      "• Remove users from groups",
      "• View member list with roles",
      "• Transfer group ownership",
      "Bulk Region Assignment:",
      "• Assign regions to entire group",
      "• All members inherit permissions",
      "• Override individual assignments",
      "Group Permissions:",
      "• Set default permissions for group",
      "• Control data visibility",
      "• Manage access levels",
      "Member List View:",
      "• Sortable member table",
      "• Filter by role, status",
      "• Quick actions per member",
      "Group Statistics:",
      "• Total members count",
      "• Active vs inactive",
      "• Data created by group",
      "• Group activity timeline"
    ]
  },
  {
    id: 11,
    title: "Admin Panel",
    icon: "⚙️",
    color: "yellow",
    action: "System administration and configuration (Admin only)",
    result: "Full system control and monitoring capabilities",
    details: [
      "Audit Log Viewer:",
      "• Complete action history",
      "• Filter by user, date, action type",
      "• Export audit logs",
      "• Search specific events",
      "Region Request Management:",
      "• Approve/deny region access requests",
      "• View pending requests queue",
      "• Auto-notification on decision",
      "Temporary Access Control:",
      "• Grant time-limited access",
      "• Set expiry date/time",
      "• Auto-revoke on expiry",
      "• Extend or revoke early",
      "System Settings:",
      "• Configure application parameters",
      "• Set default values",
      "• Enable/disable features",
      "• Performance preferences",
      "Email Notifications:",
      "• Email notification settings",
      "• Customize notification templates",
      "• Set notification preferences",
      "Permission Management:",
      "• Define role permissions",
      "• Create custom roles",
      "• View permission matrix",
      "Data Management:",
      "• Create data backups",
      "• Cleanup old data",
      "• Optimize system performance",
      "• Monitor data storage"
    ]
  },
  {
    id: 12,
    title: "Analytics",
    icon: "📊",
    color: "emerald",
    action: "View detailed reports, charts, and usage analytics",
    result: "Data-driven insights and performance metrics",
    details: [
      "Performance Insights:",
      "• Application response time trends",
      "• Activity volume over time",
      "• Error tracking and alerts",
      "• Feature-wise breakdown",
      "Usage Trends:",
      "• 7-day, 30-day, 90-day views",
      "• User activity patterns",
      "• Tool usage statistics",
      "• Peak usage hours",
      "System Health:",
      "• Application performance status",
      "• Data processing speed",
      "• Connection quality",
      "• System efficiency metrics",
      "User Activity Tracking:",
      "• Active users over time",
      "• Feature adoption rates",
      "• User engagement metrics",
      "• Session duration stats",
      "Tool Usage Statistics:",
      "• Most used GIS tools",
      "• Distance measurements count",
      "• Polygon/Circle drawings",
      "• Infrastructure additions",
      "Export Options:",
      "• Download charts as PNG",
      "• Export reports as PDF",
      "• Raw data as CSV",
      "• Scheduled report emails"
    ]
  }
];

