import { Step } from "./types";

// Steps 1-6: Login to Map Page Features
export const stepsFirstHalf: Step[] = [
  {
    id: 1,
    title: "User Login",
    icon: "🔐",
    color: "blue",
    action: "User enters credentials and clicks 'Login'",
    result: "Authentication successful, redirected to Map page",
    details: [
      "User enters email and password",
      "System validates your credentials",
      "Secure authentication process",
      "Your role and permissions loaded",
      "Region assignments retrieved",
      "Session established for 24 hours",
      "Automatic redirect to Map page",
      "Navigation customized based on your role",
    ],
  },
  {
    id: 2,
    title: "Map Page Landing",
    icon: "🗺️",
    color: "green",
    action: "Default landing page after successful login",
    result: "User sees Google Maps with infrastructure and GIS tools",
    details: [
      "Google Maps centered on India (20.5937°N, 78.9629°E)",
      "100K+ infrastructure markers loaded (viewport-based)",
      "GIS Tools Sidebar visible on left side",
      "Top Navigation Bar with accessible tabs",
      "Layer Controls panel on right",
      "Coordinates display at bottom",
      "Search box in top-right corner",
      "Profile menu and notifications visible",
      "Marker clustering enabled (1000+ items)",
      "3D view toggle available",
    ],
  },
  {
    id: 3,
    title: "Top Navigation Bar",
    icon: "🔝",
    color: "purple",
    action: "Navigate between different sections of the application",
    result: "Access to 8 main functional areas based on role",
    details: [
      "Always visible across all pages",
      "Sticky header with gradient background",
      "8 Navigation Tabs (left to right):",
      "• 🗺️ Map - Default, always active first",
      "• 🗂️ GIS Data Hub - Import/Export center",
      "• 🌐 Network Planning - Feasibility & Catalog (NEW!)",
      "• 📈 Dashboard - KPIs and statistics",
      "• 👥 Users - User management (Admin/Manager)",
      "• 👥 Groups - Group management (Admin/Manager)",
      "• ⚙️ Admin - Admin panel (Admin only)",
      "• 📊 Analytics - Reports and charts",
      "Active tab highlighted with border/color",
      "Smooth transitions between pages",
    ],
  },
  {
    id: 4,
    title: "Right Side Actions",
    icon: "🎯",
    color: "orange",
    action: "Use global search, notifications, and profile menu",
    result: "Quick access to common actions and settings",
    details: [
      "🔍 Global Search Box:",
      "• Search infrastructure, users, data",
      "• Real-time suggestions as you type",
      "• Press Enter or click to search",
      "• Results show across all modules",
      "🔔 Notifications Icon:",
      "• Bell icon with red badge counter",
      "• Shows unread notification count",
      "• Click to open dropdown panel",
      "• Instant updates when events occur",
      "👤 Profile Menu (Avatar Dropdown):",
      "• Click avatar to open menu",
      "• Options: Profile, Settings, Logout",
      "• Shows user name and role",
      "• Quick role badge display",
    ],
  },
  {
    id: 5,
    title: "Role-Based Access",
    icon: "🔒",
    color: "red",
    action: "System checks user role and applies permissions",
    result: "Navigation tabs and features filtered by role",
    details: [
      "4 User Roles with different access levels:",
      "👑 ADMIN - Full Access:",
      "• All 8 tabs visible and functional",
      "• Create/Edit/Delete all data",
      "• Manage users and assign regions",
      "• View audit logs and system settings",
      "• Access Admin panel exclusively",
      "👔 MANAGER - Most Access:",
      "• 7 tabs (no Admin panel)",
      "• Create/Edit/Delete own + team data",
      "• View all users' data",
      "• Limited user management",
      "• Can view analytics and reports",
      "🔧 TECHNICIAN - GIS Tools:",
      "• 4 tabs: Map, Data Hub, Flow, Dashboard",
      "• Create/Edit/Delete own data only",
      "• Use all GIS tools",
      "• View own analytics (read-only)",
      "👁️ VIEWER - Read-Only:",
      "• 4 tabs with view-only access",
      "• Cannot create/edit/delete",
      "• Cannot export data",
      "• View assigned regions only",
    ],
  },
  {
    id: 6,
    title: "Map Page Features",
    icon: "🌍",
    color: "teal",
    action: "Interact with map, markers, and GIS tools",
    result: "Comprehensive GIS workspace with multiple tools",
    details: [
      "Google Maps Integration:",
      "• Pan, zoom, rotate controls",
      "• Satellite/Terrain/Hybrid/Roadmap views",
      "• Street view 360° integration",
      "• 3D building toggle",
      "GIS Tools Toolbar (5 core tools):",
      "• 📏 Distance Measurement - measure line distances",
      "• 📊 Elevation Profile - terrain elevation data",
      "• 🔺 Polygon Drawing - create polygon areas",
      "• ⭕ Circle Drawing - draw circular regions",
      "• 📡 RF Sector Tool - telecom coverage sectors",
      "Network Features:",
      "• 🌐 Network Catalog - Browse infrastructure/customer folders",
      "• ✅ Feasibility Panel - Create feasibility reviews",
      "Layer Controls:",
      "• Toggle different map layers on/off",
      "• Filter by user (Admin/Manager view)",
      "Smart Loading:",
      "• Only shows data in current viewport",
      "• MVT (Vector Tiles) for network data",
      "Marker Clustering:",
      "• Groups nearby markers when zoomed out",
      "• Shows cluster count for easy viewing",
      "• Expands when you zoom in closer",
    ],
  },
];

